### ISSUE TITLE
problem with ./craft.sh

### ISSUE THREAD

**Issue by paulojr-hs** [0xf4b1/hearthstone-linux#36]
I am facing the following issue when trying to install using ./craft.sh:

Downloading Hearthstone via keg ...

Fetching http://us.patch.battle.net:1119/hsb
Downloading: 2fee0e37f96e78fd34d5e581ccfb76ac: 650 [09:05,  1.92s/]Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(: Waiting for data...            
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f87c91f6da0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='level3.blizzard.com', port=80): Max retries exceeded with url: /tpr/hs/data/2f/ee/2fee0e37f96e78fd34d5e581ccfb76ac (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87c91f6da0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paulo/hearthstone-linux/keg/bin/ngdp", line 1048, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/paulo/hearthstone-linux/keg/bin/ngdp", line 309, in fetch
    ctx.obj.fetch_versions(versions, blobs, remote_cdn, metadata_only, tags)
  File "/home/paulo/hearthstone-linux/keg/bin/ngdp", line 263, in fetch_versions
    item.fetch()
  File "/usr/lib/python3.10/site-packages/keg/core/fetcher.py", line 43, in fetch
    item = self.fetcher.remote_cdn.get_item(path)
  File "/usr/lib/python3.10/site-packages/keg/cdn.py", line 124, in get_item
    return self.get_response(final_path).raw
  File "/usr/lib/python3.10/site-packages/keg/cdn.py", line 117, in get_response
    ret = requests.get(url, stream=True)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='level3.blizzard.com', port=80): Max retries exceeded with url: /tpr/hs/data/2f/ee/2fee0e37f96e78fd34d5e581ccfb76ac (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87c91f6da0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by paulojr-hs** [comment]
I'm using Arch linux, clean installation, I installed the dependencies from the readme, I tried the command with and without sudo and in a certain part of the download I'm facing this error, could you help me? obs: it's not the first installation I've done, I've used it before and I didn't play for a while and I went to reinstall it now..

**Comment by 0xf4b1** [comment]
`Temporary failure in name resolution` looks like connection issues, either for you or the servers. I guess this will work again when you retry it

**Comment by paulojr-hs** [comment]
Ok, tranks you... I think is I think it's a problem with the servers, because my connection doesn't have any problems.
