### ISSUE TITLE
didn`t work.

### ISSUE THREAD

**Issue by NicTanghe** [0xf4b1/hearthstone-linux#59]
Hearthstone installation not found
~/git/hearthstone-linux/hearthstone ~/git/hearthstone-linux
Which region do you wish to install? [eu/us/kr/cn]: eu
Initialized in /home/tanghe/git/hearthstone-linux/hearthstone/.ngdp
Which locale do you wish to install? [deDE/enGB/enUS/esES/esMX/frFR/itIT/jaJP/koKR/plPL/ptBR/ruRU/thTH/zhCN/zhTW]: enGB
Region: eu
Online version: 29.2.2.198711.198314
Installed version: Not installed
Update required.
Downloading Hearthstone via keg ...
Fetching http://eu.patch.battle.net:1119/hsb
Downloading: 4c4bd289b8e319e333285df3374814d3: 132 [05:13, 44.00s/]Traceback (most recent call last):d7168b09a70e001d5843e43dfde8773: Fetching archives: 10/59
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/urllib3/response.py", line 737, in _error_catcher639e7f: Waiting for data...
    yield
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/urllib3/response.py", line 862, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/urllib3/response.py", line 845, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.10/http/client.py", line 482, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.10/http/client.py", line 633, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(41943040 bytes read, 226492248 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tanghe/git/hearthstone-linux/keg/bin/ngdp", line 1048, in <module>
    main()
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tanghe/git/hearthstone-linux/keg/bin/ngdp", line 309, in fetch
    ctx.obj.fetch_versions(versions, blobs, remote_cdn, metadata_only, tags)
  File "/home/tanghe/git/hearthstone-linux/keg/bin/ngdp", line 263, in fetch_versions
    item.fetch()
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/keg/core/fetcher.py", line 54, in fetch
    temp_path = self.fetcher.local_cdn.write_temp_file(item.read())
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/urllib3/response.py", line 935, in read
    data = self._raw_read(amt)
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/urllib3/response.py", line 861, in _raw_read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/tanghe/git/hearthstone-linux/venv/lib/python3.10/site-packages/urllib3/response.py", line 764, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(41943040 bytes read, 226492248 more expected)', IncompleteRead(41943040 bytes read, 226492248 more expected))
                                                                  %

**Comment by 0xf4b1** [comment]
Looks like a temporary connection error, same as in #30.
If the problem persists, you could try to remove the parameter `--cdn "http://level3.blizzard.com/tpr/hs"` inside the script and check if this helps :thinking:
